// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
	id: string;
	createdAt: number;
};

export type Meta = {
	page: number;
	total: number;
	totalPages: number;
};
